# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f64fd1782bf6e4bb78c110d8bf4b7a171359b8195b8a5a1444dab3b1a0381a8835b6ce77211d0a87de1403ab6a742c864c001b6f040572d7b9d91012780427d0

test:
  secret_key_base: 5cbb4cc5d6d274a55c3dc11fc32d4e030a52f17af74f5d9eb92b6658d725648fb6b12c364e07cb3e78ec4b90fcc3214034d5f51c5e65dee5d564e2eea16e7e79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
