# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c60ffb957a64d103f87a4c34cef1d5f976b5d1ee2c8aedc4f43994fc77c8a8c0fb5de65367ca32d2c001e0487266e997f934c000a4fbfd9dbf2a371a69d7f785

test:
  secret_key_base: 44906efda64697bd55ebe3ac204f0b11728e7283202fe1b38f6fea6752fe10aa18bc36d7fb2c279a4f80372cf3a97a65a67df1de298bdd310d85923b83161ea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
